language: rust

addons:
  apt:
    packages:
    - gcc
    - g++
    - libssl-dev
    - libcurl4-openssl-dev
    - libelf-dev
    - libdw-dev
    - binutils-dev
    - libiberty-dev
    - libsnappy-dev

rust:
  - stable
matrix:
  include:
    - rust: nightly-2017-10-03
      env: FEATURE=clippy

cache:
  directories:
  - $HOME/.cargo
  - $HOME/.local
  - $TRAVIS_BUILD_DIR/target

dist: trusty
sudo: required

env:
  global:
  - CLIPPY_VERS=0.0.165
  - CARGO_INCREMENTAL=1
  - RUSTFLAGS="-C link-dead-code"
  - CODECOV_TOKEN=90006bf6-e4b7-4825-b880-8d19c4e21c21
  matrix:
  - FEATURE=test-lib
  - FEATURE=test-doc

install:
- |
  case "$FEATURE" in
  clippy )
    cargo clippy --version | grep $CLIPPY_VERS || cargo install clippy --force --vers $CLIPPY_VERS
  ;;
  esac
- cargo install --list
script: |
  case "$FEATURE" in

  "clippy" )
      cargo clippy -- -D warnings
  ;;
  "test-lib" )
      RUST_LOG=off cargo test --tests --lib
  ;;
  "test-doc" )
      cargo test --doc -- --test-threads=2
  ;;

  esac

